/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_jnidemo_toadd */

#ifndef _Included_com_test_jnidemo_toadd
#define _Included_com_test_jnidemo_toadd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_jnidemo_toadd
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_test_jnidemo_toadd_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
